### ISSUE TITLE
HfLA Onboarding: Calendar invite

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/admin#65]
### Overview
We need to create a calendar invite for the HfLA onboarding events so that HfLA members who want to help can access the event details easily.

### Action Items
- [x] create recurring meeting for the two separate days of the onboarding
- [ ]
### Resources/Instructions
- meetup link: https://www.meetup.com/hackforla/events/
- wiki page: https://github.com/hackforla/admin/wiki/Onboarding-Events

**Comment by Rabia2219** [comment]
- meetup link: https://www.meetup.com/hackforla/events/
- Owned by: hfla-all-email
- wiki page: https://github.com/hackforla/admin/wiki/Onboarding-Events

**Comment by ExperimentsInHonesty** [comment]
2022-12-30 Sent a calendar invite from hfla-email-all to all the current panelists

You are on this calendar invite because you have been added as a panelist to the onboarding.  If you do not want to be a panelist anymore, please write to #admin channel and we will offboard you from all the resources.

The zoom login for the webinar should be in your email (it comes direct from zoom).  Search for it using the text "Panelist for Hack for LA Onboarding"  If you don't have it, write to us on the `#admin` slack channel.

Info related to onboarding can be found: 
Meetup: https://www.meetup.com/hackforla/events/
WIKI: https://github.com/hackforla/admin/wiki/Onboarding-Events 
1Password vault: HfLA Onboarding - panelists (all the links we are trying to keep private)

Note: it says weekly on Monday and Tuesday, but it's actually for the following dates only:

2023-01-03	Tuesday
2023-01-16	Monday
2023-01-31	Tuesday
2023-02-13	Monday
2023-02-28	Tuesday
2023-03-13	Monday
2023-03-28	Tuesday
2023-04-10	Monday
2023-04-25	Tuesday
2023-05-08	Monday
2023-05-23	Tuesday
2023-06-12	Monday
2023-06-27	Tuesday
2023-07-10	Monday
2023-07-25	Tuesday
2023-08-14	Monday
2023-08-29	Tuesday
2023-09-11	Monday
2023-09-26	Tuesday
2023-10-16	Monday
2023-10-24	Tuesday
2023-11-06	Monday
